server:
  port: 8084
  
spring:
  application:
    name: service-credit #(1)
  profiles:
    active:
    - dev #(2)
#MONGO
  data:
    mongodb:
      authentication-database: creditdb
      host: localhost
      port: 27017